#paste this to the bottom of your config you copy from the panel and save this in /etc/pterodactyl/

docker:
  network:
    interface: 172.22.0.1 #Node Network: edit this subnet to be one up from where you set the wings subnet (third octet)
    dns:
    - 10.255.1.31 #edit this for local dns first (pihole)
    - 1.1.1.1 #public DNS 
    name: ptero_node_network
    ispn: false
    driver: bridge
    network_mode: ptero_node_network
    is_internal: false
    enable_icc: true
    interfaces:
      v4:
        subnet: 172.22.0.0/16 #edit this subnet to be one up from where you set the wings subnet (third octet)
        gateway: 172.22.0.1 #edit this subnet to be one up from where you set the wings subnet (third octet)
